replicaCount: 3

containerPort: 8080

image:
  repository: asia-northeast3-docker.pkg.dev/dksung-gke-project/test-repo/images/test
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: LoadBalancer
  port: 80

podSecurityContext: {}

securityContext: {}

serviceAccount: 
  create: true
  automount: true
  annotations: {}
  name: ""

livenessProbe: {}
readinessProbe: {}

resources: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}