name: Deploy test app

on:
  push:
    branches:
    - "master"

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write' 
    
    runs-on: ubuntu-latest
   
    steps:
    - name: code checkout
      uses: actions/checkout@v4
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER}}
        service_account: ${{ secrets.GOOGLE_SA }}
        create_credentails_file: true

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2

    - name : gcloud login
      run : |-
        gcloud auth login 
    
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-northeast3-docker.pkg.dev
        docker build -t asia-northeast3-docker.pkg.dev/$GOOGLE_PROJECT/test-repo/images/test:latest .
        docker push asia-northeast3-docker.pkg.dev/$GOOGLE_PROJECT/test-repo/images/test:latest
      

