 name: Build and Push to Artifact Registry

 on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

 env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  REGION: asia-northeast3
  GAR_LOCATION: asia-northeast3-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/test-repo/images/test


 jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ secrets.GOOGLE_SA }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build image
        run: docker build --tag ${{ env.GAR_LOCATION }} .
        working-directory: WORKING_DIRECTORY

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}